name: TestPlugin
main: com.ethplugin.testplugin.TestPlugin
version: 0.1
description: Premier test de programmation de plugin
author: RougeDragon
commands:
  commandetest:
    description: Ma commande test
    usage: /commandetest [parametre1] [parametre2]
    permission: permission.TestPlugin
    aliases:
    - ct
    - cmdt
  settpposition:
    description: Sets a position for teleportation
    usage: /settpposition [position_name]
    permission: TestPlugin.settpposition
    aliases:
    - stp
  gototpposition:
    description: Go to position previously saved
    usage: /gototpposition [position_name]
    permission: TestPlugin.gototpposition
    aliases:
    - gtp
  removetpposition:
    description: Remove position previously saved
    usage: /removetpposition [position_name]
    permission: TestPlugin.removetpposition
    aliases:
    - rtp
  listtpposition:
    description: Gives list of positions previously saved
    usage: /listtpposition
    permission: TestPlugin.listtpposition
    aliases:
    - ltp
permissions:
  TestPlugin.*:
    description: Permissions for test plugin
    children:
      TestPlugin.settpposition: true
      TestPlugin.gototpposition: true
      TestPlugin.removetpposition: true
      TestPlugin.listtpposition: true
    TestPlugin.settpposition:
     description: Allows you set a tp position
     default: true
    TestPlugin.gototpposition:
     description: Allows you go to a tp position
     default: true
    TestPlugin.removetpposition:
     description: Allows you remove a tp position
     default: true
    TestPlugin.listtpposition:
     description: Allows you list all tp positions
     default: true
     