name: TeleportPlugin
main: com.ethplugin.teleportplugin.TeleportPlugin
version: 1.0.0
description: With this plugin, you can save locations and then teleport your player to these locations at any time.
author: RougeDragon
commands:
  settpposition:
    description: Save a position
    usage: /settpposition [position_name]
    aliases:
    - stp
  gototpposition:
    description: Go to a previously saved position
    usage: /gototpposition [position_name]
    aliases:
    - gtp
  removetpposition:
    description: Remove a position previously saved
    usage: /removetpposition [position_name]
    aliases:
    - rtp
  listtpposition:
    description: Gives list of positions previously saved
    usage: /listtpposition
    aliases:
    - ltp
