name: TestPlugin
main: com.ethplugin.testplugin.TestPlugin
version: 0.1
description: Premier test de programmation de plugin
author: RougeDragon
commands:
  commandetest:
    description: Ma commande test
    usage: /commandetest [parametre1] [parametre2]
    aliases:
    - ct
    - cmdt
  settpposition:
    description: Sets a position for teleportation
    usage: /settpposition [position_name]
    aliases:
    - stp
  gototpposition:
    description: Go to position previously saved
    usage: /gototpposition [position_name]
    aliases:
    - gtp
  removetpposition:
    description: Remove position previously saved
    usage: /removetpposition [position_name]
    aliases:
    - rtp
  listtpposition:
    description: Gives list of positions previously saved
    usage: /listtpposition
    aliases:
    - ltp
